export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const DECREASE_FROM_BASKET = "DECREASE_FROM_BASKET";
export const MODIFY_FROM_BASKET = "MODIFY_FROM_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const GET_TOTAL = "GET_TOTAL";
export const GET_USERDATA_FROM_BASKET = "GET_USERDATA_FROM_BASKET";
export const EMPTY_BASKET = "EMPTY_BASKET";
